version: '3.8'

# Prefixes:
# - cds: card-deck-server

services:
  cds:
    image: docker.pkg.github.com/cardsity/card-deck-server/cardsity-deck-server:latest
    restart: always
    networks:
      - cardsity
    depends_on:
      - cds_db
    environment:
      DJANGO_AUTOMATIC_MIGRATE: 'yes'
      DJANGO_COLLECTSTATIC: 'yes'
      SLEEP: "10"
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - cds_static:/app/static

  cds_db:
    image: mariadb
    restart: always
    networks:
      - cardsity
    environment:
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - cds_db:/var/lib/mysql

  server:
    image: docker.pkg.github.com/cardsity/game-server/cardsity-game-server:latest
    restart: always
    networks:
      - cardsity
    depends_on:
      - cds
    ports:
      - "9012:9012"
    volumes:
    - ./ssl:/app/cert

  nginx:
    build: .
    restart: always
    networks:
      - cardsity
    depends_on:
      - cds
    volumes:
      - cds_static:/var/www/deck-server:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/:/ssl/:ro
    ports:
      - "80:80"
      - "443:443"

volumes:
  cds_db:
  cds_static:

networks:
  cardsity:
